import { ConvexError, v } from 'convex/values'

import type { Doc, Id } from '../_generated/dataModel'
import { internalMutation, internalQuery } from '../_generated/server'
import { timingSafeEqual } from '../lib/crypto'
import { ACCESS_TOKEN_TTL_MS, AUTH_CODE_TTL_MS, REFRESH_TOKEN_TTL_MS, nowMs } from '../lib/time'

/**
 * Internal-only CRUD for the four OAuth token tables. Public mutations /
 * actions (`register`, `authorize`, `token`) call these to keep all writes
 * into the token tables routed through a single, auditable place.
 */

export const storeAuthCode = internalMutation({
  args: {
    code: v.string(),
    clientId: v.string(),
    userId: v.id('users'),
    redirectUri: v.string(),
    codeChallenge: v.string(),
    codeChallengeMethod: v.literal('S256'),
    scope: v.string(),
  },
  handler: async (ctx, args): Promise<Id<'oauthAuthCodes'>> => {
    return await ctx.db.insert('oauthAuthCodes', {
      ...args,
      expiresAt: nowMs() + AUTH_CODE_TTL_MS,
      used: false,
    })
  },
})

/**
 * Perform the entire database side of a successful authorization-code
 * exchange in ONE Convex transaction:
 *
 *   1. validate the code (existence, not-yet-used, not-expired, clientId,
 *      redirectUri, PKCE challenge comparison) — read-only
 *   2. read the (userId, clientId) grant sentinel — still read-only, so
 *      any throw here (e.g. a pathological two-rows case) rolls back
 *      with the code still usable for a legitimate retry
 *   3. mark the code `used`
 *   4. write the grant sentinel (insert-or-patch) — forces concurrent
 *      exchanges to conflict and retry
 *   5. revoke every non-revoked access + refresh token for (userId, clientId)
 *   6. get-or-create the synthetic session for (userId, clientId)
 *   7. insert the new access + refresh token rows
 *
 * Steps 3–7 are in the same transaction as steps 1–2. This is the ONLY
 * shape that closes the concurrent-double-authorize race. Earlier
 * versions split the token inserts out into separate mutations; under
 * that shape two parallel exchanges for different codes but the same
 * (userId, clientId) could each see an empty token table at revoke-time,
 * neither revoke the other, and both produce valid tokens. Keeping all
 * writes in one transaction + reading+writing a shared grant sentinel
 * is what guarantees Convex OCC will force a conflict-and-retry for the
 * later flow.
 *
 * **Why `expectedChallenge` is pre-computed by the caller**: `crypto.subtle.digest`
 * is NOT available in the Convex mutation isolate. Only the action runtime
 * exposes the full Web Crypto API. Test environments (Node / convex-test)
 * mask this because they run mutations in a normal V8 with full globals,
 * but production deployments would throw at runtime. So the action hashes
 * the verifier and hands us the result; the mutation only does a
 * constant-time string compare (no SubtleCrypto call).
 *
 * **Why the tokens are also pre-generated by the caller**: `crypto.getRandomValues`
 * IS available in mutations, but the action already holds the tokens to
 * return to the HTTP client, so generating them twice is pointless. The
 * mutation just takes the already-generated opaque strings and inserts
 * the rows.
 *
 * Errors propagate as ConvexError so the caller can distinguish each
 * failure mode in telemetry. The public token endpoint normalises all of
 * these to OAuth `invalid_grant` on the wire (RFC 6749 §5.2).
 */
export const exchangeCodeForTokens = internalMutation({
  args: {
    code: v.string(),
    clientId: v.string(),
    clientName: v.string(),
    redirectUri: v.string(),
    /** Caller must compute `base64url(sha256(code_verifier))` and pass it. */
    expectedChallenge: v.string(),
    /** Caller generates the two opaque bearer tokens. */
    accessToken: v.string(),
    refreshToken: v.string(),
  },
  handler: async (
    ctx,
    args,
  ): Promise<{
    userId: Id<'users'>
    scope: string
    sessionId: Id<'sessions'>
    accessRevoked: number
    refreshRevoked: number
  }> => {
    // 1. Validate the code.
    const row = await ctx.db
      .query('oauthAuthCodes')
      .withIndex('by_code', (q) => q.eq('code', args.code))
      .unique()
    if (!row) {
      throw new ConvexError({ code: 'INVALID_AUTH_CODE', message: 'code not found' })
    }
    if (row.used) {
      throw new ConvexError({ code: 'INVALID_AUTH_CODE', message: 'code already consumed' })
    }
    if (row.expiresAt < nowMs()) {
      throw new ConvexError({ code: 'INVALID_AUTH_CODE', message: 'code expired' })
    }
    if (row.clientId !== args.clientId) {
      throw new ConvexError({ code: 'CLIENT_ID_MISMATCH', message: 'client_id does not match code' })
    }
    if (row.redirectUri !== args.redirectUri) {
      throw new ConvexError({ code: 'REDIRECT_URI_MISMATCH', message: 'redirect_uri does not match code' })
    }
    // Constant-time compare of caller-supplied expectedChallenge against
    // the stored challenge. No SubtleCrypto call here on purpose.
    if (!timingSafeEqual(args.expectedChallenge, row.codeChallenge)) {
      throw new ConvexError({ code: 'PKCE_MISMATCH', message: 'code_verifier does not match stored challenge' })
    }

    // 2. Read the (userId, clientId) grant sentinel row BEFORE we mutate
    //    anything. Two reasons for this order:
    //
    //    (a) OCC: the sentinel read is what puts the grant document (or
    //        the empty index range, for the first-time exchange) into
    //        this mutation's read set. Convex's read set tracks index
    //        *intervals*, not just matched document IDs — an empty
    //        `.unique()` still registers the scanned interval. Source:
    //        `crates/database/src/reads.rs` (`ReadSet.indexed` is an
    //        `IntervalSet`; `overlaps_document` asks whether the written
    //        key falls in any tracked interval) and
    //        `crates/database/src/query/index_range.rs:~245-258` (the
    //        range scanner calls `record_indexed_directly` with the
    //        initial unfetched interval even when zero rows match).
    //        Two concurrent first-time exchanges therefore BOTH register
    //        the same interval; whichever inserts first wins, the other
    //        conflicts at commit, retries, and observes the earlier
    //        flow's tokens in step 5 below.
    //
    //    (b) Fail-safe: `.unique()` can throw (e.g., if a past bug ever
    //        produced two grant rows for the same (userId, clientId)).
    //        Reading first — before the irreversible `used: true` patch
    //        below — means a throw at this step cleanly rolls back the
    //        whole transaction and the auth code stays usable for a
    //        legitimate retry. Reading last would burn the code on any
    //        sentinel failure.
    const existingGrant = await ctx.db
      .query('oauthGrants')
      .withIndex('by_userId_and_clientId', (q) => q.eq('userId', row.userId).eq('clientId', args.clientId))
      .unique()

    // 3. Consume the code. From here on, every step is a write.
    await ctx.db.patch(row._id, { used: true })

    // 4. Write the grant sentinel so any concurrent exchange for the
    //    same (userId, clientId) conflicts on this row (or on the empty
    //    index range, for first-time exchanges) and retries.
    const grantNow = nowMs()
    if (existingGrant) {
      await ctx.db.patch(existingGrant._id, {
        version: existingGrant.version + 1,
        lastRotatedAt: grantNow,
      })
    } else {
      await ctx.db.insert('oauthGrants', {
        userId: row.userId,
        clientId: args.clientId,
        version: 1,
        lastRotatedAt: grantNow,
      })
    }

    // 5. Revoke existing tokens for (userId, clientId). After an OCC
    //    retry forced by step 4, the later flow will observe the earlier
    //    flow's rows and patch them revoked here.
    let accessRevoked = 0
    const accessRows = await ctx.db
      .query('oauthAccessTokens')
      .withIndex('by_userId_and_clientId', (q) => q.eq('userId', row.userId).eq('clientId', args.clientId))
      .collect()
    for (const t of accessRows) {
      if (t.revoked) continue
      await ctx.db.patch(t._id, { revoked: true })
      accessRevoked++
    }
    let refreshRevoked = 0
    const refreshRows = await ctx.db
      .query('oauthRefreshTokens')
      .withIndex('by_userId_and_clientId', (q) => q.eq('userId', row.userId).eq('clientId', args.clientId))
      .collect()
    for (const t of refreshRows) {
      if (t.revoked) continue
      await ctx.db.patch(t._id, { revoked: true })
      refreshRevoked++
    }

    // 6. Get-or-create the synthetic external session for (userId, clientId).
    //    Stable naming means re-authorize reuses the session; history
    //    persists across rotations. This is intentional for the CCC-22
    //    MVP — a future /revoke endpoint would need to decide whether to
    //    delete the session + history or preserve it.
    const sessionName = sessionNameFor(args.clientId, args.clientName)
    const existingSession = await ctx.db
      .query('sessions')
      .withIndex('by_user_and_sessionName', (q) => q.eq('userId', row.userId).eq('sessionName', sessionName))
      .unique()
    let sessionId: Id<'sessions'>
    const now = nowMs()
    if (existingSession) {
      await ctx.db.patch(existingSession._id, { lastSeenAt: now })
      sessionId = existingSession._id
    } else {
      sessionId = await ctx.db.insert('sessions', {
        userId: row.userId,
        sessionName,
        objective: `External MCP client: ${args.clientName}`,
        machine: 'external-mcp',
        createdAt: now,
        lastSeenAt: now,
      })
    }

    // 7. Issue the new access + refresh token rows. Both inserts happen in
    //    THIS transaction so a crash / error between them is impossible.
    await ctx.db.insert('oauthAccessTokens', {
      token: args.accessToken,
      clientId: args.clientId,
      userId: row.userId,
      sessionId,
      scope: row.scope,
      expiresAt: nowMs() + ACCESS_TOKEN_TTL_MS,
      revoked: false,
    })
    await ctx.db.insert('oauthRefreshTokens', {
      token: args.refreshToken,
      clientId: args.clientId,
      userId: row.userId,
      sessionId,
      scope: row.scope,
      expiresAt: nowMs() + REFRESH_TOKEN_TTL_MS,
      revoked: false,
    })

    return { userId: row.userId, scope: row.scope, sessionId, accessRevoked, refreshRevoked }
  },
})

/**
 * Refresh-token rotation issued atomically in a single mutation. Same
 * shape as `exchangeCodeForTokens`: the two inserts and the consumption
 * of the old refresh token all live in one transaction.
 *
 * Concurrency: two parallel rotate calls with the same old token both
 * read+patch the same `oauthRefreshTokens` document by ID, so Convex
 * OCC fires naturally on the shared document. The grant-row bump below
 * is defence-in-depth + a useful "last rotation" telemetry signal.
 */
export const rotateRefreshToken = internalMutation({
  args: {
    oldRefreshToken: v.string(),
    clientId: v.string(),
    accessToken: v.string(),
    refreshToken: v.string(),
  },
  handler: async (ctx, args): Promise<{ userId: Id<'users'>; scope: string; sessionId: Id<'sessions'> }> => {
    // 1. Validate the refresh token (read-only).
    const row = await ctx.db
      .query('oauthRefreshTokens')
      .withIndex('by_token', (q) => q.eq('token', args.oldRefreshToken))
      .unique()
    if (!row || row.revoked || row.expiresAt < nowMs()) {
      throw new ConvexError({ code: 'INVALID_REFRESH_TOKEN', message: 'refresh_token invalid, revoked, or expired' })
    }
    if (row.clientId !== args.clientId) {
      throw new ConvexError({ code: 'CLIENT_ID_MISMATCH', message: 'client_id does not match refresh token' })
    }

    // 2. Read the grant sentinel (still read-only). Same "validate,
    //    then commit" discipline as `exchangeCodeForTokens`: any throw
    //    here (e.g., a pathological `.unique()` failure) rolls back
    //    before we revoke the old refresh token, so the client can
    //    legitimately retry.
    const grant = await ctx.db
      .query('oauthGrants')
      .withIndex('by_userId_and_clientId', (q) => q.eq('userId', row.userId).eq('clientId', args.clientId))
      .unique()

    // 3. Revoke the old refresh token.
    await ctx.db.patch(row._id, { revoked: true })

    // 4. Bump the grant sentinel.
    const grantNow = nowMs()
    if (grant) {
      await ctx.db.patch(grant._id, { version: grant.version + 1, lastRotatedAt: grantNow })
    } else {
      await ctx.db.insert('oauthGrants', {
        userId: row.userId,
        clientId: args.clientId,
        version: 1,
        lastRotatedAt: grantNow,
      })
    }

    await ctx.db.insert('oauthAccessTokens', {
      token: args.accessToken,
      clientId: row.clientId,
      userId: row.userId,
      sessionId: row.sessionId,
      scope: row.scope,
      expiresAt: nowMs() + ACCESS_TOKEN_TTL_MS,
      revoked: false,
    })
    await ctx.db.insert('oauthRefreshTokens', {
      token: args.refreshToken,
      clientId: row.clientId,
      userId: row.userId,
      sessionId: row.sessionId,
      scope: row.scope,
      expiresAt: nowMs() + REFRESH_TOKEN_TTL_MS,
      revoked: false,
    })
    return { userId: row.userId, scope: row.scope, sessionId: row.sessionId }
  },
})

export const resolveAccessToken = internalQuery({
  args: { token: v.string() },
  handler: async (ctx, { token }): Promise<Doc<'oauthAccessTokens'> | null> => {
    const row = await ctx.db
      .query('oauthAccessTokens')
      .withIndex('by_token', (q) => q.eq('token', token))
      .unique()
    if (!row) return null
    if (row.revoked || row.expiresAt < nowMs()) return null
    return row
  },
})

/** The sessionName we use for external AI clients. Stable, so a Claude.ai
 *  re-authorize reuses the same synthetic session. `clientId` is included
 *  so two different AI apps authorized by the same user are distinct. */
function sessionNameFor(clientId: string, clientName: string): string {
  const safeName = clientName.replace(/[^\w .-]/g, '').slice(0, 40)
  const idSuffix = clientId.slice(0, 8)
  return `${safeName} (external/${idSuffix})`
}
